### ISSUE TITLE
Backspace の動作不具合

### ISSUE THREAD

**Issue by kakudo415** [rhysd/vim.wasm#1]
Backspace（以下BS）で文字を消すことができなかったのでご報告致します

OS : Windows 10
Browser : Firefox (プライベートブラウズも試しました)

再現方法 : 
a → 適当な文字列を打つ → BS（この時カーソルは一文字戻りますが、文字が消えません。また、戻ったカーソルにさらに文字を打つと上書きするような動きをします）

そのあと、 Esc → a → 適当な文字列を打つ → BS（この時はBS自体が利かなくなります）

**Comment by rhysd** [comment]
ご報告ありがとうございます．再現手順助かります

> a → 適当な文字列を打つ → BS（この時カーソルは一文字戻りますが、文字が消えません。また、戻ったカーソルにさらに文字を打つと上書きするような動きをします）

こちらは Vim の `--feature=tiny` デフォルトの挙動としてそうなっていたと思います．バックスペースによる文字削除はノーマルモードに戻るまで反映されません

> そのあと、 Esc → a → 適当な文字列を打つ → BS（この時はBS自体が利かなくなります）

こちらは私の手元では再現できませんでした．今夜あたりに Windows 機に Firefox を入れて試してみようと思います．

**Comment by rhysd** [comment]
tiny のデフォルト設定は一部一般的なユーザの設定とは異なっていて使いづらいので， b2b284d4c3c4549a5b39e55f5c4a2d9dd738c49e にて初期設定に少し手を入れました．この変更により

- `vi` 互換モードが無効になっているのでバックスペースで文字削除が即座に反映される
- 改行文字や行頭文字もバックスペースで削除できるようになる

はずです． https://rhysd.github.io/vim.wasm には既にデプロイしてみたので，お手数ですが再度ご確認願えませんでしょうか？

**Comment by kakudo415** [comment]
なるほど、 `--feature=tiny` オプションでそういう挙動をするわけですね。理解不足でした。
素早いご対応ありがとうございます。

**Comment by kakudo415** [comment]
今回のデプロイでどちらのやり方でも不具合は確認できませんでした。
修正ありがとうございます。

**Comment by rhysd** [comment]
いえ，普通は `--feature=tiny` を使う機会はほぼ無いと思うので，私のほうでもう少し説明を書くべきでした．ご指摘いただいたことにより該当箇所を改善することができたと思います．ありがとうございました．
