### ISSUE TITLE
vimtutor

### ISSUE THREAD

**Issue by gdcolella** [rhysd/vim.wasm#12]
Could you create a page that pre-populates this with the text of vimtutor?
http://www2.geog.ucl.ac.uk/~plewis/teaching/unix/vimtutor

This would be a really cool tool for trying out vim!

**Comment by rhysd** [comment]
Yeah, I feel it's nice idea. Let me plan it

**Comment by rhysd** [comment]
Tutor file is already included. `:e tutor` can open vimtutor buffer.
![2018-07-23 15 01 44](https://user-images.githubusercontent.com/823277/43059775-1162c024-8e89-11e8-976e-ca434b0aec25.png)

**Comment by rhysd** [comment]
Closing this since vimtutor is now included in preloaded files.
