### ISSUE TITLE
Resizing the browser window

### ISSUE THREAD

**Issue by TheKnarf** [rhysd/vim.wasm#14]
Resizing the browser window isn't triggered as resizing the terminal, instead it just squishes and stretches the rendering. 

<img width="423" alt="screen shot 2018-07-11 at 10 01 42" src="https://user-images.githubusercontent.com/213777/42558405-6d37588e-84f1-11e8-8dff-872874704fd5.png">

**Comment by rhysd** [comment]
Yeah, this is already listed in [development tasks](https://github.com/rhysd/vim.wasm/projects/2)

**Comment by rhysd** [comment]
I added implementation for this at https://github.com/rhysd/vim.wasm/commit/208446b71b7e78f414bb64a94e1aa3b0b65b3049. However, it does not work since C function called from JavaScript does not consider async call with Emterpreter. So calling `gui_wasm_resize_shell` from JavaScript fails.

**Comment by rhysd** [comment]
This was fixed as follows. I'll deploy new build today.

![tmp](https://user-images.githubusercontent.com/823277/59505877-af385080-8ee1-11e9-9298-8ca1480c00af.gif)
