### ISSUE TITLE
build from vim/vim

### ISSUE THREAD

**Issue by lunu-bounir** [rhysd/vim.wasm#16]
Hello,

Is there any instruction how to rebase from vim/vim to fetch the latest changes?

**Comment by lunu-bounir** [comment]
Here is what I did;

1. Use travis-ci.org with trzeci/emscripten:sdk-incoming-64bit image to build the whole thing
2. clone directly from the original vim/vim
3. apply patches; https://github.com/lunu-bounir/vim.wasm/blob/master/patches.sh

**Comment by lunu-bounir** [comment]
Here is the compile log; https://travis-ci.org/lunu-bounir/vim.wasm

**Comment by lunu-bounir** [comment]
Everything looks okay; https://github.com/lunu-bounir/vim.wasm/releases/

Except I am getting the following error

```
Assertion failed: The call to gui_wasm_send_key is running asynchronously. If this was intended, add the async option to the ccall/cwrap call.```

**Comment by rhysd** [comment]
I guess you wrongly built this app or your emscripten is too old. I can't say anymore from reading your comments.

**Comment by lunu-bounir** [comment]
Thanks for the prompt reply. I think am using the latest official docker file; [trzeci/emscripten:sdk-incoming-64bit](https://hub.docker.com/r/trzeci/emscripten/)

Could it be possible that I have missed to patch a file? Here is the complete list
https://github.com/lunu-bounir/vim.wasm/tree/master/patches

> I can't say anymore from reading your comments.

How about the actual log: https://api.travis-ci.org/v3/job/403079577/log.txt

**Comment by rhysd** [comment]
Why don't you simply fork this repo? I'm sorry that I don't have time to look into your setup.

**Comment by lunu-bounir** [comment]
The idea was to prepare a setup that could generate different outputs from the latest vim/vim repo (like with different color schemes or even different features). Manually generating all these combinations is not doable.

> Why don't you simply fork this repo?

With latest emscripten installed only `RELEASE=true ./build.sh` works for me.

**Comment by rhysd** [comment]
I understood what you want to do. But changing colorscheme can be done by modifiying `wasm/usr` directory. So it still doesn't need to separate patches and other `vim/vim` commits, I feel. I'm installing `emscripten` and `binaryen` directly to my environment on macOS and haven't seen the error. I'm sorry that I can't help.
