### ISSUE TITLE
colorscheme

### ISSUE THREAD

**Issue by lunu-bounir** [rhysd/vim.wasm#17]
Is there a reason why there is only a single colorscheme; https://github.com/rhysd/vim.wasm/tree/wasm/wasm/usr/local/share/vim/colors

Is it possible to have more colorschemes; https://github.com/vim/vim/tree/master/runtime/colors

**Comment by rhysd** [comment]
The same reason as #15 . We always need to consider the bundle size of the application since it is downloaded via networks.

**Comment by lunu-bounir** [comment]
I noticed your online demo throws `Error detected while processing /usr/local/share/vim/colors/desert.vim:`

So I tried to use https://github.com/vim/vim/blob/master/runtime/colors/blue.vim instead of the default one so I added the `blue.vim` to the `share/vim/colors` and edited the `vim/vimrc` file. Still got `index.js:1 Error detected while processing /usr/local/share/vim/colors/desert.vim`

**Comment by rhysd** [comment]
Yeah, I also noticed that. The error was thrown because some script in `desert.vim` is not available in tiny feature set. I don't know why the error continues to show after you change the colorscheme.

**Comment by rhysd** [comment]
Closing this as I answered.
