### ISSUE TITLE
Replacing with option c (confirm) freezes the navigator tab

### ISSUE THREAD

**Issue by Hugus** [rhysd/vim.wasm#21]
On https://rhysd.github.io/vim.wasm/ page,
I type the following sequence
`ihohoho<esc>`
`:%s/o/i/gc<enter>`

I then cannot do anything else, page seem to be "frozen".

![image](https://user-images.githubusercontent.com/5089442/44591495-27e8e780-a7be-11e8-88e6-391d2f30e480.png)

**Comment by rhysd** [comment]
Thank you for reporting this. I fixed this bug at fc22646 and will deploy the latest version soon.
