### ISSUE TITLE
Text artifacts on changes

### ISSUE THREAD

**Issue by xentripetal** [rhysd/vim.wasm#23]
**Describe the bug**
Text artifacts are visible on any large changes to text. 

**Steps To Reproduce**
Open vim.wasm, enter insert mode to remove the starter text.

**Expected behavior**
All previous text should be gone and no white marks of a previous text should be visible.

**Actual behavior**
There are white marks of the previous text

**Screenshots/DevTools console (if possible)**
https://i.imgur.com/IwlLIJv.gif

**Your environment:**
 - OS:  Windows 10
 - Browser: Firefox and Edge
 - Browser Version: 66.0.3 and 44.17763.1.0

**Additional context (if any)**
Tested with both browsers at different window sizes.
Tested on 1920x1080 and 3840x2160 resolution
Testing device has embedded graphics and a dedicated GPU

**Comment by xentripetal** [comment]
Note on further inspection, all of the artifacts seem to where the font characters went below their background highlight. Possible that the font is misaligned?

**Comment by rhysd** [comment]
I guess it's depending on your monospace font configuration of browser. Since this project uses `<canvas>` to draw screen, drawing/removing/scrolling text are implemented in TypeScript. And the implementation would not be perfect for every font.

And providing screenshot of the artifacts would be helpful to understand what is going wrong.

**Comment by xentripetal** [comment]
> And providing screenshot of the artifacts would be helpful to understand what is going wrong.

@rhysd There is already a GIF showing the issue in the original post. Should I add additional screenshots?

**Comment by rhysd** [comment]
I'm sorry I missed the link.

**Comment by rhysd** [comment]
I could also reproduce this with Firefox on macOS.

**Comment by rhysd** [comment]
I could fix this. I'll deploy new build today.

![tmp](https://user-images.githubusercontent.com/823277/59482010-d40cd380-8ea1-11e9-933c-ff339f97d926.gif)
