### ISSUE TITLE
Typing ":w foo" (and Enter) makes the tab unusable

### ISSUE THREAD

**Issue by shlomif** [rhysd/vim.wasm#24]
**Describe the bug**

Typing ":w foo" (and Enter) makes the tab unusable

**Steps To Reproduce**

:w foo and Enter

**Expected behavior**

**Actual behavior**

Tab gets stuck and nothing responds.

**Screenshots/DevTools console (if possible)**

**Your environment:**
 - OS: mageia v7 x86-64
 - Browser: firefox-66.0.3-1.mga7
 - Browser Version: 66.0.3

**Additional context (if any)**

**Comment by rhysd** [comment]
This was fixed by #30 because vim.wasm moved to new architecture omitting Emterpreter usage. 

Though saved file is still on JavaScript memory and not accessible from outside ;)

Closing.

**Comment by shlomif** [comment]
Thanks @rhysd ! But now I am getting an error dialog about window.Atomics.

**Comment by rhysd** [comment]
Yes, you need to use Chrome or enable feature flag. It is current restriction. Please see introduction in README.md.
