### ISSUE TITLE
Uncaught abort("Assertion failed: undefined")

### ISSUE THREAD

**Issue by localhostdotdev** [rhysd/vim.wasm#25]
**Describe the bug** crash

**Steps To Reproduce** write text, shift-v down arrow / up arrow, y/d, p, repeat

**Expected behavior** works fine

**Actual behavior** crashes at some point

**Screenshots/DevTools console (if possible)**

<img width="682" alt="bug" src="https://user-images.githubusercontent.com/47308085/56730055-20b41800-6757-11e9-8f93-2da4f8ae72c5.png">

**Your environment:**
 - OS: macOS
 - Browser: Chrome
 - Browser Version: 76 (canary)

**Additional context (if any)** I'm not sure exactly of the steps to reproduce

**Comment by 0b01** [comment]
This is a very important issue because I can't use vim.wasm as an adhoc text editor.

**Comment by rhysd** [comment]
This was fixed by #30 because vim.wasm moved to new architecture omitting Emterpreter usage. Closing.
