### ISSUE TITLE
Can't generate from release tarball

### ISSUE THREAD

**Issue by piranna** [rhysd/vim.wasm#31]
https://github.com/rhysd/vim.wasm/blob/97335e723d22a569b1c541db3076d50024a1c8a2/build.sh#L5-L8

Trying to generate the `vim.wasm` file from a release tarball, I get an error because there's no `.git` folder. I understand this behaviour is to prevent errors, but in that case, I think is superfluous and should be removed.

**Comment by rhysd** [comment]
The tarball link is always automatically generated by GitHub and unused for development. Please make sure to use `git clone` as ['Development' section](https://github.com/rhysd/vim.wasm#development) is saying.

```
git clone https://github.com/rhysd/vim.wasm.git
```

**Comment by rhysd** [comment]
If you're not able to use Git for some reason, please make a dummy directory at root dir.

```
mkdir .git
./build.sh
```
