### ISSUE TITLE
Cross origin isolation

### ISSUE THREAD

**Issue by HKalbasi** [rhysd/vim.wasm#43]
### What is an issue which you want to solve with your feature request?
Working in Firefox (And maybe other browsers).

### Describe the solution you'd like
- Host somewhere that support custom headers (like netlify)
- Add [coop and coep headers](https://web.dev/coop-coep/)

**Comment by hkalbasi** [comment]
Closing as duplicate of #45. Despite this being older, that gained more attraction.
