### ISSUE TITLE
Any relationship to coolwanglu/vim.js ?

### ISSUE THREAD

**Issue by captbaritone** [rhysd/vim.wasm#5]
I looked in the readme, but didn't see anything. Is there any relationship between this project and https://github.com/coolwanglu/vim.js ?

Great work! 👏

**Comment by rhysd** [comment]
As I wrote special thanks in README, vim.js was a great work. This project is not a succeeding project of vim.js, but I leaned many things from the project since I'm just a beginner of wasm toolchain (emscripten).

**Comment by captbaritone** [comment]
Ah, sorry for missing that. Thanks for pointing it out.

**Comment by rhysd** [comment]
it seems that I mistook the issue number at 8fa579f (I meant 'fix #3 and #4'). Reopening
