### ISSUE TITLE
bug? Visual-mode cursor is not removed

### ISSUE THREAD

**Issue by usagi** [rhysd/vim.wasm#6]
### Repro.

1. Write something multiline
1. Into the Visual-mode
1. Select an area
1. Do replace or something to selected area

### Screenshot

![image](https://user-images.githubusercontent.com/115972/42481635-63c4e948-841e-11e8-871d-aaaf8bbf9386.png)

**Comment by rhysd** [comment]
Thank you for reporting this. I could reproduce this and it seems a bug.

**Comment by szellmann** [comment]
Maybe related:

1.) Write sth.
2.) CTRL-V to blockwise visual mode, block-select first character of multiple lines
3.) Shift-I to block-insert multiple characters at the beginning of these lines, e.g. a few spaces for indentation. Spaces will, when entered, however not be inserted, but rather the cursor will move to the right (like pressing space in command mode).

 I'm on macOS 10.13, with Safari 11.1 and Firefox 61.0.

**Comment by rhysd** [comment]
@szellmann Thank you for reporting another case. Root cause looks the same. I will also look into it.

**Comment by rhysd** [comment]
I confirmed that this is a correct behavior when building Vim with `--with-features=tiny`.

![tmp](https://user-images.githubusercontent.com/823277/42548621-fff87bec-8502-11e8-9642-4ac6f15005ed.gif)

I agree that this looks weird behavior. But it is at least not a bug of vim.wasm. (It may be a bug of Vim itself)
